FROM python:alpine

# Alpine uses apk instead of apt-get
RUN apk add --no-cache curl

# Rest stays the same
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
EXPOSE 5000
CMD ["python", "app.py"]